run-dist:
	./build/install/app/bin/app

run-dist-valid:
	./build/install/app/bin/app ./testFiles/file1.json ./testFiles/file2.json

run-dist-invalid:
	./build/install/app/bin/app ./testFiles/missingfile1.json ./testFiles/file2.json